language: node_js
email: false
services:
  - docker
node_js:
  - 10
cache:
  directories:
    - ~/.npm
    - ~/.cache
install:
  - npm ci
script:
  - npm test
after_script:
  - docker build -t leosuncin/realworld-frontend .
  - npx semantic-release
